services:
  server:
    build: ./server
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432
    command: flask run --host 0.0.0.0 --port 5000

  client:
    container_name: client
    build: ./client
    restart: on-failure
    ports:
      - "3000:3000"
    command: serve -s build
    depends_on:
      - server

  postgres:
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - MAX_CONNECTIONS=100
      - SHARED_BUFFERS=256MB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
